In [42]:
my_list = [1,2,3]

In [43]:
import numpy as np

In [46]:
arr = np.array(my_list)

In [47]:
arr

array([1, 2, 3])

In [48]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [49]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [56]:
np.zeros(3)

array([0., 0., 0.])

In [57]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
np.ones(4)

array([1., 1., 1., 1.])

In [70]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [71]:
arr = np.arange(25)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
ranarr = np.random.randint(0,50,10)

In [75]:
ranarr

array([16, 24, 17, 38,  6, 13, 48, 13, 45,  5])

In [80]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
ranarr.max()

48

In [83]:
ranarr.min()

5

In [84]:
ranarr

array([16, 24, 17, 38,  6, 13, 48, 13, 45,  5])

In [87]:
ranarr.argmax()

6