In [24]:
import numpy as np

In [27]:
arr_2d = np.array([[5,10,15],[20,25,30],[35, 40, 45]])

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2d[2,1]

40

In [33]:
arr_2d[1][2]

30

In [34]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [37]:
arr = np.arange(1,11)

In [38]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])